### ISSUE TITLE
Spatial-View Aggregator

### ISSUE THREAD

**Issue by YuhsiHu** [TQTQliu/GeFu#3]
Hi Tianqi, thank you for your great work on the generalizable NeRF!

I find that one attention module is proposed in the `Spatial-View Aggregator`, but I do not find a related Transformer in the implementation. Could you please clarify where do you apply the attention to the features in the code?

By the way, if I understood correctly, the `Adaptive Cost Aggregation` is the omeganet [here](https://github.com/TQTQliu/GeFu/blob/main/lib/networks/gefu/network.py#L163), right?

Thank you for your time!

**Comment by TQTQliu** [comment]
Hi, thanks for your kind word!
1) For the attention module, please refer [here](https://github.com/TQTQliu/GeFu/blob/86443625c6ae69a531b81a2e672d3922d82f0e70/lib/networks/gefu/nerf.py#L101).
2) Yes, the `Adaptive Cost Aggregation` is the omeganet.

**Comment by YuhsiHu** [comment]
Thank you for your reply! This explanation helps a lot.
